import { existsSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "pathe";
import { APP_CHOICES } from "./constants.js";
import { type JwtCreds, type PortMap } from "./worktree.js";

export function renderEnv(opts: {
  slug: string;
  ports: PortMap;
  redisDb: number;
  jwt: JwtCreds;
  /** When true, write portless hostnames; when false, write http://localhost:PORT URLs. */
  portless: boolean;
  /** Required when portless is true. e.g. "dev" for branch "dev". */
  branchPrefix?: string;
}): string {
  const { slug, ports, redisDb, jwt, portless, branchPrefix } = opts;

  const host = (sub: string) => `${sub}.${branchPrefix}.dev`;
  const local = (port: number) => `http://localhost:${port}`;

  const lines: string[] = [];
  lines.push("# Generated by crbn. Do not edit by hand.");
  lines.push("# Vite/React Router auto-load this file alongside .env;");
  lines.push("# values here override .env. The user's .env is left untouched.");
  lines.push("");
  lines.push(`CARBON_WORKTREE=${slug}`);
  if (portless) lines.push("PORTLESS_TLD=dev");
  lines.push("");
  lines.push("# Internal compose ports (apps do not read these directly)");
  for (const [k, v] of Object.entries(ports)) lines.push(`${k}=${v}`);
  lines.push("");
  lines.push(
    portless
      ? "# App-facing URLs (portless hostnames)"
      : "# App-facing URLs (localhost)"
  );
  lines.push(`DOMAIN=${portless ? `${branchPrefix}.dev` : "localhost"}`);
  lines.push(
    `ERP_URL=${portless ? `https://${host("erp")}` : local(ports.PORT_ERP)}`
  );
  lines.push(
    `MES_URL=${portless ? `https://${host("mes")}` : local(ports.PORT_MES)}`
  );
  lines.push(
    `VERCEL_URL=${portless ? `https://${host("erp")}` : local(ports.PORT_ERP)}`
  );
  if (portless) lines.push(`GTM_URL=https://${host("starter")}`);
  lines.push("");
  lines.push(
    "# Supabase (per-worktree dev keys, minted from random JWT_SECRET)"
  );
  lines.push(
    `SUPABASE_URL=${portless ? `https://${host("api")}` : local(ports.PORT_API)}`
  );
  lines.push(
    `SUPABASE_DB_URL=postgresql://postgres:postgres@localhost:${ports.PORT_DB}/postgres`
  );
  lines.push("PGSSLMODE=disable");
  lines.push(`SUPABASE_JWT_SECRET=${jwt.secret}`);
  lines.push(`SUPABASE_ANON_KEY=${jwt.anonKey}`);
  lines.push(`SUPABASE_SERVICE_ROLE_KEY=${jwt.serviceKey}`);
  // OAuth callback: portless uses the shared api.carbon.dev alias; localhost
  // mode uses the well-known Supabase default port so the redirect URI is
  // predictable and can be registered in Google/Azure console once.
  const oauthBase = portless
    ? "https://api.carbon.dev"
    : "http://localhost:54321";
  lines.push(
    `SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI=${oauthBase}/auth/v1/callback`
  );
  lines.push(
    `SUPABASE_AUTH_EXTERNAL_AZURE_REDIRECT_URI=${oauthBase}/auth/v1/callback`
  );
  lines.push("");
  lines.push("# Aux services");
  lines.push("SUPABASE_CLI_SOURCE=carbon/supabase-cli:2.89.0");
  lines.push(`REDIS_DB=${redisDb}`);
  lines.push(`REDIS_URL=redis://localhost:${ports.PORT_REDIS}/${redisDb}`);
  lines.push("INNGEST_DEV=1");
  lines.push(`INNGEST_BASE_URL=http://localhost:${ports.PORT_INNGEST}`);
  // SDK advertises this as its serve URL during self-register. Must be
  // reachable from inside the inngest container (handled via extra_hosts +
  // portless CA mount in docker-compose.dev.yml).
  lines.push(
    `INNGEST_SERVE_HOST=${portless ? `https://${host("erp")}` : local(ports.PORT_ERP)}`
  );
  // Hostname (no scheme) that docker-compose maps to host-gateway inside the
  // inngest container, so the SDK URL above resolves to the dev server on the
  // host. extra_hosts only accepts fully-qualified names — no wildcards —
  // which is why we can't reuse ${DOMAIN} (e.g. `main.dev` won't match the
  // `erp.main.dev` host the SDK URL points at).
  lines.push(`INNGEST_TLS_HOST=${portless ? host("erp") : "localhost"}`);
  lines.push("");
  lines.push("# Dev auth bypass");
  lines.push("DEV_BYPASS_EMAIL=test@carbon.ms");
  lines.push("");
  return lines.join("\n");
}

export function writeEnv(worktreeRoot: string, content: string) {
  writeFileSync(join(worktreeRoot, ".env.local"), content);
}

export function syncAppPortlessConfigs(worktreeRoot: string) {
  for (const { value: appId } of APP_CHOICES) {
    const path = join(worktreeRoot, "apps", appId, "portless.json");
    if (existsSync(path)) {
      unlinkSync(path);
    }
  }
}
